version: '3.8'

services:
  db:
    image: postgres
    container_name: register-class-db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=register
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: always
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_HEAP_OPTS=-Xmx256m -Xms256m
    depends_on:
      - zookeeper
    networks:
      - kafka

networks:
  kafka:
    external:
      name: kafka
volumes:
  db:
    driver: local